import Head from "next/head"
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import SpotifyWebApi from "spotify-web-api-js";

let s = new SpotifyWebApi()


export default function dashboard() {
  const [p, setP] = useState([])
  useEffect(() => {
    const queryString = window.location.search;
    const urlParams = new URLSearchParams(queryString);
    const accessToken = urlParams.get('access_token');
    const refreshToken = urlParams.get('refresh_token');
    s.setAccessToken(accessToken);
  });

  const fetchData = () => {
    s.getMe() // note that we don't pass a user id
    .then(
      function (data) {
        setP(data.display_name)
      },
      function (err) {
        console.error(err);
      }
    );
  } 

  useEffect(() => {
    fetchData()
  }, [])

    return (
      <div className={styles.container}>
        <Head>
          <title>Dashboard </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to your dashboard, {p}!
          </h1> 
        </main>
  
        <footer className={styles.footer}>
          <a
            href="https://www.linkedin.com/in/danielbohen/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Created by Daniel Bohen
          </a>
        </footer>
      </div>
    )
  }