import Head from "next/head"
import styles from '../styles/Home.module.css'

export default function dashboard() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to your dashboard!
          </h1> 
        </main>
  
        <footer className={styles.footer}>
          <a
            href="https://www.linkedin.com/in/danielbohen/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Created by Daniel Bohen
          </a>
        </footer>
      </div>
    )
  }