import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import React from 'react'
require('dotenv').config(); 

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Playlistify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Playlistify!
        </h1>

        <p className={styles.description}>
          Get started by logging in {' '}
          <Link href="/api/login" passHref><b>here</b></Link>
        </p>
      </main> 

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/danielbohen/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Daniel Bohen
        </a>
      </footer>
    </div>
  )
}
